apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-generator-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nimishmehta8779/eks-gitops.git
    targetRevision: main
    path: apps/load-generator

  destination:
    server: https://kubernetes.default.svc
    namespace: team-alpha-apps

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
    - /status/replicas
    - /status/observedGeneration
